### ISSUE TITLE
Run as a different user id

### ISSUE THREAD

**Issue by markwallsgrove** [frekele/docker-ant#42]
Running `1.10.0-jdk8` as a different user id yields the following error:
```bash
docker-compose -f docker-compose-dev.yml run -u 1000 build /bin/bash
s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied
```

**Comment by frekele** [comment]
Hi @markwallsgrove ,

You could be a little more detailed.
Show me your complete log so I can help.
